spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.133.252:33306/countyfarmdb?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: supervise
    password: supervisedb@321
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位 # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 2
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1
        # 最大活跃连接数，负数为不限制
        max-active: 20



uploadpath:
urlPath: